language: rust

rust:
    - stable
    - beta

install:
    - sudo pip install virtualenv

script: make test

# Need sudo as python is root owned in rust builders
sudo: true

notifications:
    email: false
